### ISSUE TITLE
Более простой способ локализации предметов

### ISSUE THREAD

**Issue by Oleg720** [russian-harbor/russian_harbor_game#3]
Можно использовать этот (https://github.com/CasimirKaPazi/vortoj) мод. Благодаря ему, будет только один файл, в котором будут содержаться переводы для всех модов сразу.

**Comment by codexp** [comment]
Это не практично для добавленных модов, так как они находятся в разных репозиториях.
Можно подумать использовать этот мод для самого сабгэйма майнтеста и его модов.
Хотя и тут я думаю что это не совсем хорошо, так как таким образом ломается модульность.
И я не вижу особых преимуществ которые облегчили бы перевод модов.

@Kluver-bereg что ты думаешь об этом?

**Comment by Kluver-bereg** [comment]
Этот мод не смотрел, но один раз я пытался объединить весь перевод в один файл. Только использовал другой мод. (мод писал  narrnika. Мод выкладывали на форуме в этой теме  https://forum.minetest.net/viewtopic.php?f=23&t=14423 . Сейчас этого мода уже не нашел ) . В начале показалось удобно, но поддерживать нестандартные алгоритмы очень тяжело (На сервере перевод в одном файле был месяца три, потом сделал откат). Думаю надо придерживаться принятых стандартов.

**Comment by codexp** [comment]
я того же мнения

**Comment by codexp** [comment]
спасибо за продолжение!

**Comment by codexp** [comment]
кстати, вот мод локализации самой игры:
https://github.com/minetest-mods/mtg_i18n
